from __future__ import annotations

from copy import deepcopy


FAMILY_DEFINITIONS = {
    "object_authorization": {
        "family_id": "object_authorization",
        "title": "Object Authorization",
        "category": "authorization",
        "required_features": ["has_path_object_id|has_query_object_id"],
        "recommended_tools": ["auth_test_access"],
        "expected_evidence": ["same_object_access", "cross_user_2xx", "high_response_similarity"],
        "default_vuln_type": "bola",
        "noise_penalty_hint": 0.08,
        "feasibility_hint": 0.92,
    },
    "collection_access_control": {
        "family_id": "collection_access_control",
        "title": "Collection Access Control",
        "category": "authorization",
        "required_features": ["is_collection_like"],
        "recommended_tools": ["auth_test_access"],
        "expected_evidence": ["cross_user_collection_access", "high_response_similarity"],
        "default_vuln_type": "generic_access_control",
        "noise_penalty_hint": 0.18,
        "feasibility_hint": 0.82,
    },
    "privileged_function_access": {
        "family_id": "privileged_function_access",
        "title": "Privileged Function Access",
        "category": "authorization",
        "required_features": ["is_privileged"],
        "recommended_tools": ["auth_test_access"],
        "expected_evidence": ["low_privileged_role_gets_2xx", "privileged_function_reached"],
        "default_vuln_type": "vertical_privilege",
        "noise_penalty_hint": 0.09,
        "feasibility_hint": 0.9,
    },
    "self_scope_cross_user_access": {
        "family_id": "self_scope_cross_user_access",
        "title": "Self Scope Cross User Access",
        "category": "authorization",
        "required_features": ["is_self_scoped"],
        "recommended_tools": ["auth_test_access"],
        "expected_evidence": ["same_level_cross_user_access", "high_response_similarity"],
        "default_vuln_type": "horizontal_privilege",
        "noise_penalty_hint": 0.35,
        "feasibility_hint": 0.62,
    },
    "property_level_authorization": {
        "family_id": "property_level_authorization",
        "title": "Property Level Authorization",
        "category": "authorization",
        "required_features": ["has_sensitive_body_fields"],
        "recommended_tools": ["property_mutation_test"],
        "expected_evidence": ["sensitive_field_accepted", "protected_property_mutated"],
        "default_vuln_type": "property_level_authorization",
        "noise_penalty_hint": 0.14,
        "feasibility_hint": 0.86,
    },
    "mass_assignment": {
        "family_id": "mass_assignment",
        "title": "Mass Assignment",
        "category": "authorization",
        "required_features": ["has_body_fields", "has_sensitive_body_fields"],
        "recommended_tools": ["property_mutation_test"],
        "expected_evidence": ["unexpected_field_binding", "sensitive_field_accepted"],
        "default_vuln_type": "mass_assignment",
        "noise_penalty_hint": 0.2,
        "feasibility_hint": 0.83,
    },
    "excessive_data_exposure": {
        "family_id": "excessive_data_exposure",
        "title": "Excessive Data Exposure",
        "category": "exposure",
        "required_features": ["is_exposure_prone_get"],
        "recommended_tools": ["data_exposure_test"],
        "expected_evidence": ["sensitive_keys_exposed", "unnecessary_fields_returned"],
        "default_vuln_type": "excessive_data_exposure",
        "noise_penalty_hint": 0.18,
        "feasibility_hint": 0.8,
    },
    "authentication_weakness": {
        "family_id": "authentication_weakness",
        "title": "Authentication Weakness",
        "category": "authorization",
        "required_features": ["has_auth_semantics"],
        "recommended_tools": ["auth_probe_entrypoints", "auto_provision"],
        "expected_evidence": ["auth_surface_present", "bootstrap_path_available"],
        "default_vuln_type": "authentication_weakness",
        "noise_penalty_hint": 0.25,
        "feasibility_hint": 0.72,
    },
    "resource_abuse_rate_limit": {
        "family_id": "resource_abuse_rate_limit",
        "title": "Resource Abuse / Rate Limit",
        "category": "resource",
        "required_features": ["has_auth_semantics|has_search_semantics"],
        "recommended_tools": ["resource_abuse_test"],
        "expected_evidence": ["bounded_burst_not_throttled", "no_429_or_lockout"],
        "default_vuln_type": "unrestricted_resource_consumption",
        "noise_penalty_hint": 0.22,
        "feasibility_hint": 0.78,
    },
    "invalid_transition": {
        "family_id": "invalid_transition",
        "title": "Invalid Transition",
        "category": "business_logic",
        "required_features": ["has_workflow_verbs"],
        "recommended_tools": ["logic_test"],
        "expected_evidence": ["invalid_transition_accepted", "workflow_state_bypass"],
        "default_vuln_type": "workflow_abuse",
        "noise_penalty_hint": 0.16,
        "feasibility_hint": 0.77,
    },
    "repeated_sensitive_action": {
        "family_id": "repeated_sensitive_action",
        "title": "Repeated Sensitive Action",
        "category": "business_logic",
        "required_features": ["has_workflow_verbs"],
        "recommended_tools": ["logic_test"],
        "expected_evidence": ["repeated_sensitive_action_allowed"],
        "default_vuln_type": "workflow_abuse",
        "noise_penalty_hint": 0.18,
        "feasibility_hint": 0.74,
    },
    "cross_role_workflow_abuse": {
        "family_id": "cross_role_workflow_abuse",
        "title": "Cross Role Workflow Abuse",
        "category": "business_logic",
        "required_features": ["has_workflow_verbs", "has_auth_semantics"],
        "recommended_tools": ["logic_test"],
        "expected_evidence": ["cross_role_workflow_access", "invariant_violation"],
        "default_vuln_type": "workflow_abuse",
        "noise_penalty_hint": 0.15,
        "feasibility_hint": 0.79,
    },
    "body_input_injection": {
        "family_id": "body_input_injection",
        "title": "Body Input Injection",
        "category": "injection",
        "required_features": ["has_body_fields"],
        "recommended_tools": ["injection_test"],
        "expected_evidence": ["attack_vs_baseline_diff", "reflection_or_sink_signal"],
        "default_vuln_type": "injection",
        "noise_penalty_hint": 0.2,
        "feasibility_hint": 0.81,
    },
    "query_input_injection": {
        "family_id": "query_input_injection",
        "title": "Query Input Injection",
        "category": "injection",
        "required_features": ["has_query_params"],
        "recommended_tools": ["injection_test"],
        "expected_evidence": ["attack_vs_baseline_diff", "reflection_or_sink_signal"],
        "default_vuln_type": "injection",
        "noise_penalty_hint": 0.18,
        "feasibility_hint": 0.82,
    },
    "reflection_or_template_sink": {
        "family_id": "reflection_or_template_sink",
        "title": "Reflection Or Template Sink",
        "category": "injection",
        "required_features": ["has_query_params|has_body_fields"],
        "recommended_tools": ["reflection_probe", "injection_test"],
        "expected_evidence": ["reflection_detected", "unescaped_reflection|template_error_signal"],
        "default_vuln_type": "injection",
        "noise_penalty_hint": 0.19,
        "feasibility_hint": 0.76,
    },
    "url_fetch_or_ssrf": {
        "family_id": "url_fetch_or_ssrf",
        "title": "URL Fetch Or SSRF",
        "category": "network",
        "required_features": ["has_url_field"],
        "recommended_tools": ["generic_anomaly_probe"],
        "expected_evidence": ["url_field_accepts_external_target", "unexpected_fetch_behavior"],
        "default_vuln_type": "ssrf",
        "noise_penalty_hint": 0.32,
        "feasibility_hint": 0.45,
    },
    "security_misconfiguration": {
        "family_id": "security_misconfiguration",
        "title": "Security Misconfiguration",
        "category": "config",
        "required_features": ["is_privileged|is_doc_or_inventory_like|is_versioned"],
        "recommended_tools": ["misconfiguration_test"],
        "expected_evidence": ["dangerous_methods_or_headers", "weak_cors|debug_leak|internal_url_leak"],
        "default_vuln_type": "security_misconfiguration",
        "noise_penalty_hint": 0.17,
        "feasibility_hint": 0.8,
    },
    "improper_assets_management": {
        "family_id": "improper_assets_management",
        "title": "Improper Assets Management",
        "category": "inventory",
        "required_features": ["is_versioned"],
        "recommended_tools": ["version_diff_test"],
        "expected_evidence": ["deprecated_exposed_path_detected", "undocumented_version_paths"],
        "default_vuln_type": "improper_assets_management",
        "noise_penalty_hint": 0.14,
        "feasibility_hint": 0.82,
    },
    "documentation_inventory_leak": {
        "family_id": "documentation_inventory_leak",
        "title": "Documentation Inventory Leak",
        "category": "inventory",
        "required_features": ["is_doc_or_inventory_like"],
        "recommended_tools": ["version_diff_test"],
        "expected_evidence": ["documentation_path_exposed", "inventory_surface_visible"],
        "default_vuln_type": "documentation_inventory_leak",
        "noise_penalty_hint": 0.11,
        "feasibility_hint": 0.88,
    },
    "generic_anomaly_probe": {
        "family_id": "generic_anomaly_probe",
        "title": "Generic Anomaly Probe",
        "category": "fallback",
        "required_features": [],
        "recommended_tools": ["noop_outcome"],
        "expected_evidence": ["anomalous_behavior_observed"],
        "default_vuln_type": "generic_access_control",
        "noise_penalty_hint": 0.5,
        "feasibility_hint": 0.25,
    },
}


def get_family_definition(family_id: str) -> dict:
    return deepcopy(FAMILY_DEFINITIONS[str(family_id or "").strip()])


def all_family_definitions() -> list[dict]:
    return [deepcopy(value) for value in FAMILY_DEFINITIONS.values()]
