ALTER TABLE judge_decisions
ADD COLUMN IF NOT EXISTS raw_selected_key TEXT,
ADD COLUMN IF NOT EXISTS raw_score DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS raw_reason TEXT,
ADD COLUMN IF NOT EXISTS resolution_mode VARCHAR(64);
