ALTER TABLE test_sessions
ADD COLUMN IF NOT EXISTS budget_requests_total INTEGER DEFAULT 200,
ADD COLUMN IF NOT EXISTS budget_requests_used INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS budget_time_total INTEGER DEFAULT 1800,
ADD COLUMN IF NOT EXISTS budget_time_used INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_rounds INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS rounds_completed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS allowed_test_classes_json TEXT,
ADD COLUMN IF NOT EXISTS last_strategy_json TEXT,
ADD COLUMN IF NOT EXISTS stop_reason TEXT;

ALTER TABLE experiment_runs
ADD COLUMN IF NOT EXISTS profile VARCHAR DEFAULT 'mixed';

ALTER TABLE experiment_results
ADD COLUMN IF NOT EXISTS bopla_findings INTEGER,
ADD COLUMN IF NOT EXISTS confirmed_findings INTEGER,
ADD COLUMN IF NOT EXISTS confirmed_bola INTEGER,
ADD COLUMN IF NOT EXISTS confirmed_bopla INTEGER;
